[mongodb]
mongodb-dev.dsecops88.online

[catalogue]
catalogue-dev.dsecops88.online

[redis]
redis-dev.dsecops88.online

[user]
user-dev.dsecops88.online

[cart]
cart-dev.dsecops88.online

[mysql]
mysql-dev.dsecops88.online

[shipping]
shipping-dev.dsecops88.online

[rabbitmq]
rabbitmq-dev.dsecops88.online

[payment]
payment-dev.dsecops88.online

[frontend]
frontend-dev.dsecops88.online

[all:vars]
ansible_user=ec2-user 
ansible_password=DevOps321
MONGODB_HOST= mongodb-dev.dsecops88.online
CATALOGUE_HOST= catalogue-dev.dsecops88.online
REDIS_HOST= redis-dev.dsecops88.online
USER_HOST=  user-dev.dsecops88.online
CART_HOST=  cart-dev.dsecops88.online
MYSQL_HOST= mysql-dev.dsecops88.online
SHIPPING_HOST= shipping-dev.dsecops88.online
RABBITMQ_HOST= rabbitmq-dev.dsecops88.online
PAYMENT_HOST=  payment-dev.dsecops88.online